#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinitely with a sleep 2 in between each iteration.

# Infinite loop using true command
while :
do
  echo "To infinity and beyond"
  sleep 2
done

